[package]
name = "muxmate"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
clap = { version = "4.5.16", features = ["derive"] }
dirs = "5.0.1"
colored = "2.1.0"
tmux_interface = "0.3.2"
